# Generated by Django 5.0.6 on 2024-06-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(blank=True, null=True, verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_doc',
            field=models.IntegerField(blank=True, null=True, verbose_name='Precio por docena'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_media',
            field=models.IntegerField(blank=True, null=True, verbose_name='Precio por mitad'),
        ),
    ]
